# Usa una JDK ufficiale come base
FROM eclipse-temurin:17-jdk

# Crea una directory per l'app
WORKDIR /app

# Copia il jar già compilato (modifica il nome secondo il tuo progetto)
COPY target/shoPOP-0.0.1-SNAPSHOT.jar app.jar

# Espone la porta su cui gira Spring Boot
EXPOSE 8080

# Comando di avvio
ENTRYPOINT ["java", "-jar", "app.jar"]
